### PR TITLE
scroll+responsive for school computer screen size

### PR DESCRIPTION
**Pull request by AppleEpic101**
fixed grade box size at different screen sizes. added scrollbar.

### CODE REVIEW

**Comment by refact0r** [comment]
nah you cannot just name a class topG

**Comment by AppleEpic101** [comment]
> nah you cannot just name a class topG

shorthand for topGrades. parent class for grades.

**Comment by refact0r** [comment]
🤔🤔🤔🤔🤔🤔🤔

**Comment by refact0r** [comment]
sorry but that does not fit the naming convention
please use dashes instead of camelcase and don't shorten words
for parent/container class make it "something-container"

**Comment by AppleEpic101** [comment]
> sorry but that does not fit the naming convention please use dashes instead of camelcase and don't shorten words for parent/container class make it "something-container"

then, my love for cobratate reigns supreme

**Pull request closed without merging**
